sonar.projectKey=ArmetalFe
sonar.projectName=Armetal Frontend
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.login=sqp_70025c6f815a3f6c6233d45888cc534bd74591de

# Source code
sonar.sources=src

# Tests
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js

# Exclusions
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,src/__tests__/setupTests.js

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8