sonar.projectKey=rekory-frontend
sonar.projectName=REKORY FRONTEND
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=squ_f9a4ee8bb910143010758f87f0f730398e181a77

sonar.exclusions=node_modules/**,build/**,coverage/**