
sonar.projectKey=client
sonar.projectName=Client
sonar.host.url=http://localhost:9000

sonar.token=squ_5ffe301b0de65629d6193914db7ec1217af64053


sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info