
import {
  BiMessageSquareDetail,
} from "react-icons/bi";

export const planColumns = [
  {
    header: "Plan Name",
    accessor: "plan",
  },
  {
    header: "Tier",
    accessor: "tier",
  },
  {
    header: "Employees",
    accessor: "employees",
  },
  {
    header: "Price / Month",
    accessor: "priceText",
  },
  {
    header: "Extra Employee Charge",
    accessor: "extra",
  },
  {
    header: "Features",
    accessor: "features",
  },
  {
    header: "Status",
    accessor: "status",
  },
];

export const planData = [
  {
    plan: "Basic Plan",
    tier: "Basic",
    employees: "01-10",
    price: 1500,
    priceText: "1500/-",
    extra: "-",
    features: "4 Features",
    status: "Active",
  },
  {
    plan: "Pro Plan",
    tier: "Pro",
    employees: "11-20",
    price: 2000,
    priceText: "2000/-",
    extra: "200/-",
    features: "5 Features",
    status: "Active",
  },
  {
    plan: "Enterprise",
    tier: "Enterprise",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Custom Plan",
    tier: "Custom ",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Basic Plan",
    tier: "Basic",
    employees: "01-10",
    price: 1500,
    priceText: "1500/-",
    extra: "-",
    features: "4 Features",
    status: "Active",
  },
  {
    plan: "Pro Plan",
    tier: "Pro",
    employees: "11-20",
    price: 2000,
    priceText: "2000/-",
    extra: "200/-",
    features: "5 Features",
    status: "Active",
  },
  {
    plan: "Enterprise",
    tier: "Enterprise",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Custom Plan",
    tier: "Custom ",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Basic Plan",
    tier: "Basic",
    employees: "01-10",
    price: 1500,
    priceText: "1500/-",
    extra: "-",
    features: "4 Features",
    status: "Active",
  },
  {
    plan: "Pro Plan",
    tier: "Pro",
    employees: "11-20",
    price: 2000,
    priceText: "2000/-",
    extra: "200/-",
    features: "5 Features",
    status: "Active",
  },
  {
    plan: "Enterprise",
    tier: "Enterprise",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Custom Plan",
    tier: "Custom ",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Basic Plan",
    tier: "Basic",
    employees: "01-10",
    price: 1500,
    priceText: "1500/-",
    extra: "-",
    features: "4 Features",
    status: "Active",
  },
  {
    plan: "Pro Plan",
    tier: "Pro",
    employees: "11-20",
    price: 2000,
    priceText: "2000/-",
    extra: "200/-",
    features: "5 Features",
    status: "Active",
  },
  {
    plan: "Enterprise",
    tier: "Enterprise",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Custom Plan",
    tier: "Custom ",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
    {
    plan: "Pro Plan",
    tier: "Pro",
    employees: "11-20",
    price: 2000,
    priceText: "2000/-",
    extra: "200/-",
    features: "5 Features",
    status: "Active",
  },
  {
    plan: "Enterprise",
    tier: "Enterprise",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Custom Plan",
    tier: "Custom ",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
    {
    plan: "Pro Plan",
    tier: "Pro",
    employees: "11-20",
    price: 2000,
    priceText: "2000/-",
    extra: "200/-",
    features: "5 Features",
    status: "Active",
  },
  {
    plan: "Enterprise",
    tier: "Enterprise",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
   {
    plan: "Custom Plan",
    tier: "Custom ",
    employees: "100+",
    price: 3500,
    priceText: "3500/-",
    extra: "300/-",
    features: "8 Features",
    status: "Active",
  },
];

export const planCards = [
  {
    title: "Total Plans",
    count: "03",
    icon: <BiMessageSquareDetail />,
    backgroundColor: "#E8EDFF",
    iconColor: "#4F6EF7",
  },
  {
    title: "Monthly Revenue",
    count: " 2500.00/-",
    icon: <BiMessageSquareDetail />,
    backgroundColor: "#FFF2E1",
    iconColor: "#F59E0B",
  },
  {
    title: "Lowest Plan",
    count: " 1500.00/-",
    icon: <BiMessageSquareDetail />,
    backgroundColor: "#E7F8EC",
    iconColor: "#22C55E",
  },
  {
    title: "Highest Plan",
    count: " 3500.00/-",
    icon: <BiMessageSquareDetail />,
    backgroundColor: "#FFE8E8",
    iconColor: "#EF4444",
  },
];