# Generated by Django 4.2.15 on 2025-09-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
