# Generated by Django 4.2.15 on 2026-02-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0012_company_amount_per_employee_company_initial_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('IN', 'Income'), ('OUT', 'Expense')], max_length=3)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('REIMBURSEMENT', 'Reimbursement'), ('TRAVEL', 'Travel'), ('FOOD', 'Food'), ('SUBSCRIPTION', 'Subscription'), ('OTHER', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='superadmin.company')),
            ],
        ),
    ]
