# Generated by Django 5.2.1 on 2025-06-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='temp_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_image1_url', models.URLField(blank=True, null=True)),
                ('passport_image2_url', models.URLField(blank=True, null=True)),
                ('insurance_image_url', models.URLField(blank=True, null=True)),
                ('work_permit_urls', models.JSONField(blank=True, default=list)),
                ('contract_urls', models.JSONField(blank=True, default=list)),
                ('certificate_urls', models.JSONField(blank=True, default=list)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee_db')),
            ],
        ),
    ]
