# Generated by Django 5.2 on 2025-06-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_tempupload_empdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='empbankpaymentmodel',
            name='housing_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empbankpaymentmodel',
            name='transportation',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
