# Generated by Django 5.2 on 2025-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_empbankpaymentmodel_housing_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='phno',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
