# Generated by Django 5.2.1 on 2025-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_db_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empbankpaymentmodel',
            name='document',
        ),
        migrations.AddField(
            model_name='empbankpaymentmodel',
            name='bank_proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='bank_proof/'),
        ),
    ]
