# Generated by Django 5.2.1 on 2025-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_empbankpaymentmodel_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='iqama_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
