# Generated by Django 5.2 on 2025-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_db_iqama_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='total_leave',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
