# Generated by Django 5.2 on 2025-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employee_db_total_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='total_leave',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
