# Generated by Django 5.2 on 2025-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_schedulereminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='contract_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_db',
            name='idcard',
            field=models.ImageField(blank=True, null=True, upload_to='idcard_pics/'),
        ),
        migrations.AddField(
            model_name='employee_db',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('hr', 'HR'), ('manager', 'Manager')], default='employee', max_length=20),
        ),
    ]
