# Generated by Django 4.2.15 on 2025-08-21 11:24

from django.db import migrations
import shared.dataencrpt


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employee_db_contract_expiry_date_employee_db_idcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbankpaymentmodel',
            name='account_number',
            field=shared.dataencrpt.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='empbankpaymentmodel',
            name='pan_number',
            field=shared.dataencrpt.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='empbankpaymentmodel',
            name='swift_code',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='empbankpaymentmodel',
            name='uan_epf_number',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='address',
            field=shared.dataencrpt.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='email',
            field=shared.dataencrpt.EncryptedEmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='employee_id',
            field=shared.dataencrpt.EncryptedCharField(editable=False, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='insurance_number',
            field=shared.dataencrpt.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='iqama_number',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='name',
            field=shared.dataencrpt.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='passport_number',
            field=shared.dataencrpt.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='password',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='phno',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
