# Generated by Django 4.2.15 on 2025-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_empbankpaymentmodel_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='employee_id',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
