# Generated by Django 4.2.15 on 2025-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_db_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
