# Generated by Django 4.2.15 on 2025-08-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_employee_db_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereminder',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
