# Generated by Django 4.2.15 on 2025-09-03 04:22

from django.db import migrations
import shared.dataencrpt


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_db_aadar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='iqama_number',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
