# Generated by Django 4.2.15 on 2025-09-03 04:31

from django.db import migrations
import shared.dataencrpt


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_db_iqama_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='iqama_number',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
