# Generated by Django 4.2.15 on 2025-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_alter_employee_db_iqama_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='visa_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
