# Generated by Django 4.2.15 on 2025-09-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_employee_db_visa_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbankpaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('online', 'Online'), ('by cash', 'By Cash'), ('cheque', 'Cheque')], max_length=10),
        ),
    ]
