# Generated by Django 4.2.15 on 2025-11-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_empbankpaymentmodel_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='paid_leave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='total_leave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
