# Generated by Django 4.2.15 on 2025-11-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_employee_db_paid_leave_alter_employee_db_total_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='paid_leave',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='total_leave',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
