# Generated by Django 4.2.15 on 2025-11-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employee_db_paid_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='paid_leave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='total_leave',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
