# Generated by Django 4.2.15 on 2025-11-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_db_paid_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='name_search',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
