# Generated by Django 4.2.15 on 2026-02-17 08:37

from django.db import migrations
import shared.dataencrpt


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_employee_db_name_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='insurance_number',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee_db',
            name='passport_number',
            field=shared.dataencrpt.EncryptedCharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
