# Generated by Django 4.2.15 on 2026-02-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_alter_employee_db_insurance_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbankpaymentmodel',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('by cash', 'By Cash'), ('cheque', 'Cheque')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_increments', to='employee.employee_db')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
