# Generated by Django 4.2.15 on 2026-05-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_alter_empbankpaymentmodel_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='employee_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
