# Generated by Django 4.2.15 on 2026-08-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_employee_db_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_db',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
