# Generated by Django 4.2.15 on 2026-08-11 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0028_employee_db_deleted_at_employee_db_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_db',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
