# Generated by Django 4.2.15 on 2026-09-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_alter_employee_db_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_db',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employee_db',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
