# Generated by Django 4.2.15 on 2025-11-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='from_date_type',
            field=models.CharField(choices=[('forenoon', 'Forenoon'), ('afternoon', 'Afternoon'), ('full', 'Full Day')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date_type',
            field=models.CharField(choices=[('forenoon', 'Forenoon'), ('afternoon', 'Afternoon'), ('full', 'Full Day')], default='full', max_length=10),
        ),
    ]
