# Generated by Django 4.2.15 on 2026-08-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_employee_db_deleted_at_employee_db_is_deleted'),
        ('leave', '0002_leaverequest_from_date_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('maternity', 'Maternity'), ('others', 'Others')], max_length=20)),
                ('total_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('used_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remaining_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee.employee_db')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
