const avatars = [
  "https://i.pravatar.cc/100?img=12",
  "https://i.pravatar.cc/100?img=32",
  "https://i.pravatar.cc/100?img=45",
  "https://i.pravatar.cc/100?img=56",
];

export const projectData = [
  {
    id: 1,
    category: "WEBSITE DESIGN_VARIANT",
    title: "MediOra – Insurance Agency Website",
    date: "22 July 2026",
    status: "InProgress",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 2,
    category: "WEBSITE DESIGN_ONSITE",
    title: "Chicking – Franchise Website",
    date: "22 July 2026",
    status: "Completed",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 3,
    category: "MOBILE APP_VARIANT",
    title: "Infit – Trainer Booking Mobile App",
    date: "22 July 2026",
    status: "InProgress",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 4,
    category: "WEB APP DESIGN_OFFICE",
    title: "ABC – Broadband Dashboard",
    date: "22 July 2026",
    status: "InProgress",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 5,
    category: "WEB APP DESIGN_VARIANT",
    title: "Rekory – HR Management Web APP",
    date: "22 July 2026",
    status: "InProgress",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 6,
    category: "WEBSITE DESIGN_ONSITE",
    title: "Architect Asif – Portfolio Website",
    date: "22 July 2026",
    status: "Completed",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 7,
    category: "WEBSITE DESIGN_VARIANT",
    title: "ARM_SBC – Ecommerce Website",
    date: "22 July 2026",
    status: "InProgress",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  {
    id: 8,
    category: "WEBSITE DESIGN_VARIANT",
    title: "MediOra – Insurance Agency Website",
    date: "22 July 2026",
    status: "InProgress",
    priority: "High",
    members: avatars,
    memberCount: 9,
  },
  
];

export default projectData;