# Generated by Django 4.2.15 on 2025-10-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0020_alter_empbankpaymentmodel_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('punch_type', models.CharField(choices=[('on_site', 'On Site'), ('variant', 'Variant')], default='on_site', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('employees', models.ManyToManyField(blank=True, related_name='projects', to='employee.employee_db')),
            ],
        ),
    ]
