# Generated by Django 4.2.15 on 2025-11-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='punch_type',
            field=models.CharField(choices=[('on_site', 'On Site'), ('variant', 'Variant'), ('bench', 'Bench')], default='on_site', max_length=20),
        ),
    ]
