# Generated by Django 4.2.15 on 2026-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
