# Generated by Django 4.2.15 on 2026-09-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_employee_db_blood_group_employee_db_country'),
        ('project', '0006_project_priority_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_leads',
            field=models.ManyToManyField(blank=True, related_name='team_lead_projects', to='employee.employee_db'),
        ),
    ]
