# Generated by Django 5.2 on 2025-07-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_time_in_attendancesession_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50, null=True),
        ),
    ]
