# Generated by Django 5.2 on 2025-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
