# Generated by Django 4.2.15 on 2025-10-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_punch_in_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
