# Generated by Django 4.2.15 on 2025-11-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_employee_db_name_search'),
        ('attendance', '0007_hourlylocationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourlylocationlog',
            options={'ordering': ['-logged_at']},
        ),
        migrations.AlterField(
            model_name='hourlylocationlog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee_db'),
        ),
    ]
