# Generated by Django 4.2.15 on 2026-08-10 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_hourlylocationlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlylocationlog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
