# Generated by Django 4.2.15 on 2026-08-24 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0008_alter_hourlylocationlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('company_off', 'Company Off')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hourlylocationlog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
