# Generated by Django 4.2.15 on 2026-08-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0015_alter_subscriptionplan_name'),
        ('attendance', '0010_attendancecorrectionrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('report_file', models.FileField(upload_to='attendance_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='superadmin.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeeattendancereport',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='unique_company_attendance_report'),
        ),
    ]
