# Generated by Django 5.2 on 2025-06-13 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicholiday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='superadmin.company'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('company', 'date')},
        ),
    ]
