# Generated by Django 5.2 on 2025-07-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_publicholiday_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholiday',
            name='date',
            field=models.DateField(),
        ),
    ]
