# Generated by Django 5.2 on 2025-07-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_alter_publicholiday_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicholiday',
            options={'ordering': ['date']},
        ),
    ]
