# Generated by Django 4.2.15 on 2026-02-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0005_publicholiday_day_alter_publicholiday_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholiday',
            name='holiday_type',
            field=models.CharField(blank=True, choices=[('public', 'Public Holiday'), ('religious', 'Religious Holiday'), ('company', 'Company Holiday'), ('optional', 'Optional/Restricted Holiday'), ('bank', 'Bank Holiday'), ('regional', 'Cultural/Regional Holiday'), ('observance', 'Observance/Non-Leave Day'), ('company_off_day', 'Company Off Day'), ('second_saturday', 'Second Saturday')], max_length=20, null=True),
        ),
    ]
