# Generated by Django 4.2.15 on 2026-05-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_alter_publicholiday_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholiday',
            name='holiday_type',
            field=models.CharField(blank=True, choices=[('public', 'Public Holiday'), ('company', 'Company Holiday'), ('company_off_day', 'Company Off Day'), ('second_saturday', 'Second Saturday')], max_length=20, null=True),
        ),
    ]
