# Generated by Django 4.2.15 on 2026-08-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0007_alter_publicholiday_holiday_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='off_day_weekday',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
