# Generated by Django 5.2 on 2025-06-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_companysubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterUniqueTogether(
            name='companysubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(default='unpaid', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='companysubscription',
            unique_together={('company', 'month', 'year')},
        ),
    ]
