# Generated by Django 5.2 on 2025-07-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_impersonationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, choices=[('IN', 'India'), ('US', 'United States'), ('AE', 'United Arab Emirates'), ('SG', 'Singapore'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('JP', 'Japan'), ('CN', 'China'), ('AU', 'Australia'), ('CA', 'Canada')], max_length=3, null=True),
        ),
    ]
