# Generated by Django 5.2 on 2025-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload PNG logo only.', null=True, upload_to='company_logos/'),
        ),
    ]
