# Generated by Django 4.2.15 on 2025-08-21 11:24

from django.db import migrations, models
import shared.dataencrpt


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=shared.dataencrpt.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=shared.dataencrpt.EncryptedCharField(editable=False, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=shared.dataencrpt.EncryptedCharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, choices=[('IN', 'India'), ('US', 'United States'), ('AE', 'United Arab Emirates'), ('SG', 'Singapore'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('JP', 'Japan'), ('CN', 'China'), ('AU', 'Australia'), ('CA', 'Canada')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_password',
            field=shared.dataencrpt.EncryptedCharField(editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=shared.dataencrpt.EncryptedEmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=shared.dataencrpt.EncryptedCharField(max_length=255),
        ),
    ]
