# Generated by Django 4.2.15 on 2025-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_alter_company_address_alter_company_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_password',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
