# Generated by Django 4.2.15 on 2025-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_alter_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the company location', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the company location', null=True),
        ),
    ]
