# Generated by Django 4.2.15 on 2025-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_company_latitude_company_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, help_text='Upload PNG or SVG logo.', null=True, upload_to='company_logos/'),
        ),
    ]
