# Generated by Django 4.2.15 on 2026-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='amount_per_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Advance amount paid during company onboarding (not linked to subscription)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
