# Generated by Django 4.2.15 on 2026-02-26 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_company_amount_per_employee_company_initial_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='basic_salary_percent',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Basic salary percentage of CTC', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='company',
            name='half_day_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Half day working hours', max_digits=4),
        ),
        migrations.AddField(
            model_name='company',
            name='house_allowance_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='company',
            name='special_allowance_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='company',
            name='transport_allowance_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='company',
            name='working_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Total working hours per day', max_digits=4),
        ),
    ]
