# Generated by Django 5.2 on 2025-06-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_employee_db_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OnHold', 'OnHold'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='pending', max_length=10)),
                ('salary_date', models.DateField(auto_now_add=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_increment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('housing_allowance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transportation', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('tds_deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('cod', 'Cash on Delivery'), ('cheque', 'Cheque')], max_length=10, null=True)),
                ('tax_regime', models.CharField(blank=True, choices=[('old', 'Old Regime'), ('new', 'New Regime')], max_length=10, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee_db')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
