# Generated by Django 5.2 on 2025-07-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='payslip_file',
            field=models.FileField(blank=True, null=True, upload_to='payslips/'),
        ),
    ]
