# Generated by Django 4.2.15 on 2025-09-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employeepayrollrecord_hr1_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepayrollrecord',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('by cash', 'By Cash'), ('cheque', 'Cheque')], max_length=10, null=True),
        ),
    ]
