# Generated by Django 4.2.15 on 2026-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employeepayrollrecord_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='days_present',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='lop_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='lop_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='working_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
