# Generated by Django 4.2.15 on 2026-05-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employeepayrollrecord_days_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='incentive_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='incentive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='incentive_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
