# Generated by Django 4.2.15 on 2026-08-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_employeepayrollrecord_incentive_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='deduction_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeepayrollrecord',
            name='deduction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
