# Generated by Django 5.2.1 on 2025-06-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
    ]
