# -------------employee attendance------------------



# list out employee attendance for admin
###
GET http://127.0.0.1:8000/api/admin/attendance/?department_id=87
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTk3Nzg4LCJpYXQiOjE3ODc1Njg5ODgsImp0aSI6IjZhMDkxMmVmOTNlMjQ3M2M5NGRlODE1YmYxMmZiOGUwIiwidXNlcl9pZCI6NCwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.D_eI07KfkmepJrLF0yiXe50YKscFMDFi_vhO4I03IJ0

# lst todays punch in punch outs
###
GET http://127.0.0.1:8000/api/attendance/today/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTk3Nzg4LCJpYXQiOjE3ODc1Njg5ODgsImp0aSI6IjZhMDkxMmVmOTNlMjQ3M2M5NGRlODE1YmYxMmZiOGUwIiwidXNlcl9pZCI6NCwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.D_eI07KfkmepJrLF0yiXe50YKscFMDFi_vhO4I03IJ0


# attendance detail view(hr admin)

###
# GET http://178.248.112.16:8001/api/admin/attendance/31/
GET http://127.0.0.1:8000/api/admin/attendance/351/?date=2026-02-11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTk3Nzg4LCJpYXQiOjE3ODc1Njg5ODgsImp0aSI6IjZhMDkxMmVmOTNlMjQ3M2M5NGRlODE1YmYxMmZiOGUwIiwidXNlcl9pZCI6NCwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.D_eI07KfkmepJrLF0yiXe50YKscFMDFi_vhO4I03IJ0

# list out employee attendance for admin
###
GET http://127.0.0.1:8000/api/admin/attendance/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTk3Nzg4LCJpYXQiOjE3ODc1Njg5ODgsImp0aSI6IjZhMDkxMmVmOTNlMjQ3M2M5NGRlODE1YmYxMmZiOGUwIiwidXNlcl9pZCI6NCwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.D_eI07KfkmepJrLF0yiXe50YKscFMDFi_vhO4I03IJ0

#================================MOBILE  APP==========

### Swipe (Punch In/Out) -FOR EMPLOYEE


POST http://127.0.0.1:8000/api/attendance/swipe/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3NTg0Nzk5LCJpYXQiOjE3ODc1NTU5OTksImp0aSI6ImQ0OTZiNWU3OTYwODRhNzE4MmIxZDhkMjBmODliZThiIiwidXNlcl9pZCI6NywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjp0cnVlfQ.HXPuqoW4LTYjWthQdko8uYaFZ8bUKzPHyc6NqKq4CTs
Content-Type: application/json

{
  "latitude": 7.23568,
  "longitude": 10.2356
}


# list todays punch in punch outs
###
GET http://178.248.112.16:8001/api/attendance/today/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY3MTY3MjcwLCJpYXQiOjE3NjcxNjM2NzAsImp0aSI6IjBiZjZmYThjODMyMDQ4N2I5MTkxNDM3YTUyMWMyY2NjIiwidXNlcl9pZCI6IjUwMSIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlLCJpc19ociI6dHJ1ZX0.jSbYcpNFoym46a7DrAPN1ipRMJtsdOVIVPeSnCOMZqY

#api for getting employees attendance details
### 
GET http://localhost:8000/api/attendance/summary/?month=2025-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzODY1MzQ1LCJpYXQiOjE3NTM4NjE3NDUsImp0aSI6ImZkMGI2ZWQwMmYwNDRmMjM5YTNmNjExMjNlNjA0MzNjIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.YI9aiNaDDaX_uz1XpPTGxfIYdPVkggdib5yRDZeR1qA

###punchout note
PATCH http://localhost:8000/api/attendance/add-note/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzODc0NjAyLCJpYXQiOjE3NTM4NzEwMDIsImp0aSI6ImIwZDgyODljNmIzZDRmMGE4Njk5MmIwZWZjZThhM2I2IiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.QHGVfWwW1urfQxTr8CHGpGN11jsn3WwzeafVplp2fAo

{
  "note": "Left early due to a dentist appointment"
}

###
GET http://178.248.112.16:8001/api/admin/attendance/351/?date=2026-02-04
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcyNDQyNjUzLCJpYXQiOjE3NzI0MzkwNTMsImp0aSI6IjUzYTliYTU1YTVkNjQzNTI4MDM2ZDhkMGY4YTRjZGQ3IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.sAfalR6BiMHhvA09x8N-G3H9lLEBllVem0gLWYkiSwY

###attendance summary
GET http://127.0.0.1:8000/api/employee-attendance/summary/?year=2026&month=08
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3OTIyMzc1LCJpYXQiOjE3ODc4OTM1NzUsImp0aSI6IjA0ZTE2NTE0YzlhZjRkZDg4ZGE0MTk4ZmZiNTBiNzZlIiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.rOfQ5OEsFqHzd4qbXa8YGD4KTBanswM5Mvvf8q9fBAc


###

PATCH http://127.0.0.1:8000/api/attendance/update/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3OTIyMzc1LCJpYXQiOjE3ODc4OTM1NzUsImp0aSI6IjA0ZTE2NTE0YzlhZjRkZDg4ZGE0MTk4ZmZiNTBiNzZlIiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.rOfQ5OEsFqHzd4qbXa8YGD4KTBanswM5Mvvf8q9fBAc
Content-Type: application/json

{
    "employee": 4,
    "date": "2026-07-31",
    "attendance_type": "paid",
    "remark": "work from home"
}