@baseUrl = http://178.248.112.16:8001/api/admindashboard/


# Get Dashboard Counts
GET {{baseUrl}}counts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzA2MDE1LCJpYXQiOjE3NjQzMDI0MTUsImp0aSI6IjIzZTJlYzMzMzA1MDRmN2Y4YmVkYWNiOTMxMWEzNjY4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.v8aC12f7XNNiTQEnkH7r8G1s1Yq0HQPmipgb5TwvJMU
Content-Type: application/json

###

# Get Reimbursement Counts
GET {{baseUrl}}reimbursement/counts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzA2MDE1LCJpYXQiOjE3NjQzMDI0MTUsImp0aSI6IjIzZTJlYzMzMzA1MDRmN2Y4YmVkYWNiOTMxMWEzNjY4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.v8aC12f7XNNiTQEnkH7r8G1s1Yq0HQPmipgb5TwvJMU
Content-Type: application/json

###

# Get Reimbursement Month-wise Counts
GET {{baseUrl}}reimbursement/monthwise/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzkxOTc5LCJpYXQiOjE3NjQzODgzNzksImp0aSI6ImQ5MzRjNzhjMzA5NTRiMTc5MjNiYmQxMmQ3M2Q3OGIyIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.AXiYJrxpwHv16OKQFJbgYEA2WaYtWp5MRs35JXNm98k
Content-Type: application/json

###

# Get Department Dashboard Summary
GET {{baseUrl}}department/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzExMTA0LCJpYXQiOjE3NjQzMDc1MDQsImp0aSI6Ijc4ZWQ1ZWE0ODEwNDQyYTNiZjFmYzljN2U2NjNkYzc4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.-VIDY4U-2ha6-Q3qTBrwIJkKzRZM4KbM3M1rjfymWdM
Content-Type: application/json

###

# Get Recent Employees
GET {{baseUrl}}recentemployees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzExMTA0LCJpYXQiOjE3NjQzMDc1MDQsImp0aSI6Ijc4ZWQ1ZWE0ODEwNDQyYTNiZjFmYzljN2U2NjNkYzc4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.-VIDY4U-2ha6-Q3qTBrwIJkKzRZM4KbM3M1rjfymWdM
Content-Type: application/json

###

# Get Contract Expiry Employees (30 days)
GET {{baseUrl}}contract-expiry/30-days/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzExMTA0LCJpYXQiOjE3NjQzMDc1MDQsImp0aSI6Ijc4ZWQ1ZWE0ODEwNDQyYTNiZjFmYzljN2U2NjNkYzc4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.-VIDY4U-2ha6-Q3qTBrwIJkKzRZM4KbM3M1rjfymWdM
Content-Type: application/json

###

# Get Simple Notifications
GET {{baseUrl}}simple-notifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzE3NjMxLCJpYXQiOjE3NjQzMTQwMzEsImp0aSI6IjZmNzk2YmU0NWUyMjQ2OWRhNDMyNjMwOWYxMGFkOGYzIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.hvxbe0q3qvBvoLf7BQT4utpq0NMZATSMHvvq2Zz8RsE
Content-Type: application/json

###

# Get Today Employee Stats
GET {{baseUrl}}today-employee-stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzE3NjMxLCJpYXQiOjE3NjQzMTQwMzEsImp0aSI6IjZmNzk2YmU0NWUyMjQ2OWRhNDMyNjMwOWYxMGFkOGYzIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.hvxbe0q3qvBvoLf7BQT4utpq0NMZATSMHvvq2Zz8RsE
Content-Type: application/json

###

# Get Holiday Summary
GET {{baseUrl}}holiday-summary/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzE3NjMxLCJpYXQiOjE3NjQzMTQwMzEsImp0aSI6IjZmNzk2YmU0NWUyMjQ2OWRhNDMyNjMwOWYxMGFkOGYzIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.hvxbe0q3qvBvoLf7BQT4utpq0NMZATSMHvvq2Zz8RsE
Content-Type: application/json


###

# Get project employee count
GET {{baseUrl}}project/employee-count/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzEzMzY5LCJpYXQiOjE3NjQzMDk3NjksImp0aSI6IjFhNjdjZDMxNDVhNDQwZmVhYjQ1MTZkOGE2ZDQ2MzI4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.ofDl6fqxfL8ewnc5OE6jkBoKVbuAK9yaUhXvjAtjQIQ
Content-Type: application/json
