# @baseUrl = http://178.248.112.16:8001/api/admindashboard/
@baseUrl = http://127.0.0.1:8000/api/admindashboard/

# Get Dashboard Counts
GET {{baseUrl}}counts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
Content-Type: application/json

###

# Get Reimbursement Counts
GET {{baseUrl}}reimbursement/counts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
Content-Type: application/json

###

# Get Reimbursement Month-wise Counts
GET {{baseUrl}}reimbursement/monthwise/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzkxOTc5LCJpYXQiOjE3NjQzODgzNzksImp0aSI6ImQ5MzRjNzhjMzA5NTRiMTc5MjNiYmQxMmQ3M2Q3OGIyIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.AXiYJrxpwHv16OKQFJbgYEA2WaYtWp5MRs35JXNm98k
Content-Type: application/json

###

# Get Department Dashboard Summary
GET {{baseUrl}}department/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzExMTA0LCJpYXQiOjE3NjQzMDc1MDQsImp0aSI6Ijc4ZWQ1ZWE0ODEwNDQyYTNiZjFmYzljN2U2NjNkYzc4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.-VIDY4U-2ha6-Q3qTBrwIJkKzRZM4KbM3M1rjfymWdM
Content-Type: application/json

###

# Get Recent Employees
GET {{baseUrl}}recentemployees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzExMTA0LCJpYXQiOjE3NjQzMDc1MDQsImp0aSI6Ijc4ZWQ1ZWE0ODEwNDQyYTNiZjFmYzljN2U2NjNkYzc4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.-VIDY4U-2ha6-Q3qTBrwIJkKzRZM4KbM3M1rjfymWdM
Content-Type: application/json

###

# Get Contract Expiry Employees (30 days)
GET {{baseUrl}}contract-expiry/30-days/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzExMTA0LCJpYXQiOjE3NjQzMDc1MDQsImp0aSI6Ijc4ZWQ1ZWE0ODEwNDQyYTNiZjFmYzljN2U2NjNkYzc4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.-VIDY4U-2ha6-Q3qTBrwIJkKzRZM4KbM3M1rjfymWdM
Content-Type: application/json

###

# Get Simple Notifications
GET {{baseUrl}}simple-notifications/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MzE3NjMxLCJpYXQiOjE3NjQzMTQwMzEsImp0aSI6IjZmNzk2YmU0NWUyMjQ2OWRhNDMyNjMwOWYxMGFkOGYzIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.hvxbe0q3qvBvoLf7BQT4utpq0NMZATSMHvvq2Zz8RsE
Content-Type: application/json

###

# Get Today Employee Stats
GET {{baseUrl}}today-employee-stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
Content-Type: application/json


###

# # Get Holiday Summary
# GET {{baseUrl}}holiday-summary/
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
# Content-Type: application/json


###

# Get project employee count
GET {{baseUrl}}project/count/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
Content-Type: application/json

###weekly attendance status
GET {{baseUrl}}weekly-attendance/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
Content-Type: application/json

### monthly payrol
GET {{baseUrl}}payroll/monthly-summary/?year=2026
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NzIyOTYzLCJpYXQiOjE3ODY2OTQxNjMsImp0aSI6IjRkNWFmNDE1Y2VlMzQ3YjdhNWQ1Yzk5OWEzZGY5ZTM0IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.18dTFX56urfUtfjLf5jP5GMmBSA0N9LFShxJKGnhjUU
Content-Type: application/json


### upcoming holidays
GET {{baseUrl}}dashboard/upcoming-holidays-birthdays/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NTUxNjI3LCJpYXQiOjE3ODY1MjI4MjcsImp0aSI6ImQ3Y2VjMjBkYWE5YTQ2YjViNDUwMTc0MzZlNmUyNjM1IiwidXNlcl9pZCI6MiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.KL1ivgLdp6-vqxR6qVuMVqfBIAgcH50ScFACdhIzdFQ
Content-Type: application/json


###  holidays list
GET {{baseUrl}}holidays/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NjIwOTc5LCJpYXQiOjE3ODY1OTIxNzksImp0aSI6IjQ1M2VjMjc3ZDIzOTQ0MjNhZGU5ZGE2ZGRmOGIwNGU5IiwidXNlcl9pZCI6NCwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.C9Abe8v6i1ZIFEPIl5T-ptiMGwSmmAaRiNvUu7TpjsA
Content-Type: application/json

