#api for generating token pair
###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "snv_arm_kak_117",
  "password": "password1234"
}

# api for getiing employees with department id
###
GET http://178.248.112.16:8001/api/employees/dep/87/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNzI5MDQxLCJpYXQiOjE3NjM3MjU0NDEsImp0aSI6IjMxODc2N2FmMDI3NDQ0NTNiYWU4MjVmM2NkMjIzOTQzIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.sFYB5_d-J6pHXDE3-WQqTI4t6CfJxsO5Mboxv-mWnQ8


### HR Admin: List Tasks by Employee ID
GET http://178.248.112.16:8001/api/admin/tasks/employee/343/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYzNzkwMTcwLCJpYXQiOjE3NjM3ODY1NzAsImp0aSI6ImVmOWJhNjBlYjU2NDQwZGU5M2Q3MjZjZTBlZTJlMmI4IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.1szSQEsMsvuZdgISM5xtKt-eDPk6Vi71TkRBcK7MXfI
