###LOGIN TO OBTAIN THE TOKEN PAIRS-FOR COMAPNY

POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "snv_arm_kak_117",
  "password": "password1234"
}
###create finance record category

POST http://178.248.112.16:8001/api/finance/categories/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxODM0Mjc0LCJpYXQiOjE3NzE4MzA2NzQsImp0aSI6IjEzNzM0MTE2NGYyNjQzMDFhYzM5ZjhhMzE3ZTczNmI5IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.3sgN54RsLfNwdG0JAlRm82CZemQZoSzDOf-r5ln7wJg
Content-Type: application/json

{
  "name": "Petrol",
  "payment_type": "OUT"
}
###create finance record

POST http://178.248.112.16:8001/api/finance/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMTgxOTUzLCJpYXQiOjE3NzAxNzgzNTMsImp0aSI6IjA3N2I0MTE2OGE1ZTRkMzFhMzVjMmVmZWM3OTliNjY2IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.GX1_iNUHxRGyH0x9eOJgUaKZAypY3UC66lOvGlMCz8U
Content-Type: application/json

{
  "date": "2026-01-25",
  "amount": 1500,
  "payment_type": "OUT",
  "category": "FOOD",
  "note": "Team lunch"
}

###
GET http://178.248.112.16:8001/api/finance/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxNTcyNzA5LCJpYXQiOjE3NzE1NjkxMDksImp0aSI6IjY4YzQzZDg4OTc0NDQ4MmQ4YjM4MDhmY2M1Y2ZkODJhIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.vKlZJYRMVcgY3qf1e2-GgExgYw33kS0WaIHutxgfIU8