# -----REIMBURSMENT MODULE------

###add 
POST http://178.248.112.16:8001/api/reimbursements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMTc5MzE0LCJpYXQiOjE3NzAxNzU3MTQsImp0aSI6IjJjOWViMjUyNWRkNzQ5MzBiYjVhMWVhMzI3Mzk3Njc0IiwidXNlcl9pZCI6NTAxLCJpc19zdXBlcmFkbWluIjpmYWxzZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6dHJ1ZSwiaXNfaHIiOnRydWV9.WlL1aPJqvaeNpA1JXZqCljrq_fmeNn2aXMuc8q0pmLE
Content-Type: multipart/form-data

{
  "expense_category": "TRAVEL",
  "to_mail": "manager@example.com",
  "note": "Taxi fare",
  "date": "2025-08-23",
  "amount": "100.50",
  "uploaded_images": ["<file1>", "<file2>"]
}

###list
GET http://178.248.112.16:8001/api/reimbursements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTM3NTI0LCJpYXQiOjE3NTU5MzM5MjQsImp0aSI6IjIzM2YzYjQ4ODgwNDRkOGFiYWI1OWZmNjU5NTY0NmQ2IiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.ib5BAbyjtBs2zhxHJvXwauLIoRObe42u9Yae6hDwVc4
Content-Type: application/json


###retrieve single record
GET http://178.248.112.16:8001/api/reimbursements/141/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyOTQ5OTM5LCJpYXQiOjE3NjI5NDYzMzksImp0aSI6IjA0ZDFlMDc1MDAxZDRkMzlhNzViYWUzNmVkZjhkNzA0IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.oJc2hxRBG476he5VT7tFdafNgJwY3KD7db0gULZyISk
Content-Type: application/json


###list by department
GET http://178.248.112.16:8001/api/reimbursements/department/16/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MTAzOTg5LCJpYXQiOjE3NTYxMDAzODksImp0aSI6IjEwYTM3N2U1NGZlMDRiM2NhOWRlZDg0YzUwMzBjMGM1IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.Qz_3MCiQu1yvYmV6Q3z4lBk6mdHyjZKVoW87MVXhOt8
Content-Type: application/json


### update status by admin
PATCH http://178.248.112.16:8001/api/reimbursements/157/   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcwMTgwODA1LCJpYXQiOjE3NzAxNzcyMDUsImp0aSI6IjU3OWY0YTk5YmFiZTQ3M2JhYTI2Y2NkNTY0MDhhNTI2IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.X2o-F8M1qcTgOJ43P5xzIYmOf7X_bX2DsBuQY2YX4XY
Content-Type: application/json

{
  "status": "Approve"
}

### Get reimbursements grouped by date
GET http://178.248.112.16:8001/api/reimbursements/grouped/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDk5OTI1LCJpYXQiOjE3NTYwOTYzMjUsImp0aSI6ImVlZWE5MzE4YmI4NDQzZTdhNjYzZGQ5ZmI2OTJhYThlIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.0kBTS1wWLMJS2dAypCpqj7B1_yGMgjDIF_Yy8Xd9KaM




### 1️⃣ List logged-in employee reimbursements
GET http://178.248.112.16:8001/api/reimbursements/my-reimbursements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzgzOTYxLCJpYXQiOjE3NTYzODAzNjEsImp0aSI6ImU1ZTg1ZGI4NTdhMzQyYzg4NGI4ODA4M2ZlN2Y1ZDMxIiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.OsyrBCizOWZrIkWZurycQSMeiRNbLPBVbojcfS_4kP8
Content-Type: application/json

###

### 2️⃣ Retrieve a single reimbursement by ID
GET http://178.248.112.16:8001/api/reimbursements/my-reimbursements/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzgzOTYxLCJpYXQiOjE3NTYzODAzNjEsImp0aSI6ImU1ZTg1ZGI4NTdhMzQyYzg4NGI4ODA4M2ZlN2Y1ZDMxIiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.OsyrBCizOWZrIkWZurycQSMeiRNbLPBVbojcfS_4kP8
Content-Type: application/json

###

### 3️⃣ Delete a single reimbursement by ID
DELETE http://178.248.112.16:8001/api/reimbursements/my-reimbursements/1/
Authorization: Bearer {{accessToken}}
Content-Type: application/json
