import { FaEdit, FaTrash } from "react-icons/fa";

export const employeeColumns = [
  {
    header: "Sl No",
    accessor: "id",
  },
  {
    header: "Employee Name",
    accessor: "name",
  },
  {
    header: "Username",
    accessor: "username",
  },
  {
    header: "Phone Number",
    accessor: "phone",
  },
  {
    header: "Employee ID",
    accessor: "employeeId",
  },
  {
    header: "Designation",
    accessor: "designation",
  },
  {
    header: "Department",
    accessor: "department",
  },
  {
    header: "Status",
    accessor: "status",
  },
  {
    header: "Action",
    accessor: "action",
    sortable: false,
  },
];

export const employeeData = [
  {
    id: 1,
    image: "https://i.pravatar.cc/150?img=1",
    name: "John Smith",
    email: "john.smith@gmail.com",
    username: "johnsmith",
    phone: "+91 9876543210",
    employeeId: "EMP001",
    designation: "HR Manager",
    department: "HR",
    status: "Present",
  },
  {
    id: 2,
    image: "https://i.pravatar.cc/150?img=2",
    name: "Emma Johnson",
    email: "emma@gmail.com",
    username: "emmajohnson",
    phone: "+91 9876543211",
    employeeId: "EMP002",
    designation: "UI Designer",
    department: "Design",
    status: "Absent",
  },
  {
    id: 3,
    image: "https://i.pravatar.cc/150?img=3",
    name: "Michael Brown",
    email: "michael@gmail.com",
    username: "michael",
    phone: "+91 9876543212",
    employeeId: "EMP003",
    designation: "Frontend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 4,
    image: "https://i.pravatar.cc/150?img=4",
    name: "Sophia Wilson",
    email: "sophia@gmail.com",
    username: "sophia",
    phone: "+91 9876543213",
    employeeId: "EMP004",
    designation: "Backend Developer",
    department: "IT",
    status: "Present",
  },
  {
    id: 5,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 6,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 7,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 8,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 9,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 10,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
    {
    id: 5,
    image: "https://i.pravatar.cc/150?img=5",
    name: "William Taylor",
    email: "william@gmail.com",
    username: "william",
    phone: "+91 9876543214",
    employeeId: "EMP005",
    designation: "QA Engineer",
    department: "Testing",
    status: "Absent",
  },
  {
    id: 6,
    image: "https://i.pravatar.cc/150?img=6",
    name: "Olivia Davis",
    email: "olivia@gmail.com",
    username: "olivia",
    phone: "+91 9876543215",
    employeeId: "EMP006",
    designation: "Business Analyst",
    department: "BA",
    status: "Present",
  },
  {
    id: 7,
    image: "https://i.pravatar.cc/150?img=7",
    name: "James Miller",
    email: "james@gmail.com",
    username: "james",
    phone: "+91 9876543216",
    employeeId: "EMP007",
    designation: "Project Manager",
    department: "Management",
    status: "Present",
  },
  {
    id: 8,
    image: "https://i.pravatar.cc/150?img=8",
    name: "Charlotte Moore",
    email: "charlotte@gmail.com",
    username: "charlotte",
    phone: "+91 9876543217",
    employeeId: "EMP008",
    designation: "Accountant",
    department: "Finance",
    status: "Absent",
  },
  {
    id: 9,
    image: "https://i.pravatar.cc/150?img=9",
    name: "Daniel Thomas",
    email: "daniel@gmail.com",
    username: "daniel",
    phone: "+91 9876543218",
    employeeId: "EMP009",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    status: "Present",
  },
  {
    id: 11,
    image: "https://i.pravatar.cc/150?img=10",
    name: "Amelia White",
    email: "amelia@gmail.com",
    username: "amelia",
    phone: "+91 9876543219",
    employeeId: "EMP010",
    designation: "Support Engineer",
    department: "Support",
    status: "Present",
  },
];