# Generated by Django 4.2.15 on 2025-08-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0014_alter_employee_db_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(choices=[('TRAVEL', 'Travel Expenses'), ('ACCOMMODATION', 'Accommodation'), ('MEALS', 'Meals & Daily Allowance'), ('SUPPLIES', 'Office Supplies & Equipment'), ('TRAINING', 'Training & Certifications'), ('ENTERTAINMENT', 'Client Entertainment'), ('BILLS', 'Internet & Phone Bills'), ('HEALTHCARE', 'Healthcare'), ('MISC', 'General / Miscellaneous')], max_length=50)),
                ('to_mail', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('On Hold', ' On Hold'), ('In Verification', 'In Verification'), ('Approve', 'Approve')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='employee.employee_db')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reimbursements/')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reimbursement.reimbursement')),
            ],
        ),
    ]
