# Generated by Django 4.2.15 on 2025-08-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('On Hold', ' On Hold'), ('In Verification', 'In Verification'), ('Approve', 'Approve')], max_length=50, null=True),
        ),
    ]
