# Generated by Django 4.2.15 on 2025-09-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_alter_reimbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('On Hold', ' On Hold'), ('In Verification', 'In Verification'), ('Approve', 'Approve')], default='On Hold', max_length=50, null=True),
        ),
    ]
