# Generated by Django 4.2.15 on 2025-09-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_alter_reimbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='to_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
