# Generated by Django 4.2.15 on 2025-09-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0004_alter_reimbursement_to_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='expense_category',
            field=models.CharField(choices=[('TRAVEL', 'Travel Expenses'), ('ACCOMMODATION', 'Accommodation'), ('MEALS', 'Meals & Daily Allowance'), ('SUPPLIES', 'Office Supplies & Equipment'), ('TRAINING', 'Training & Certifications'), ('ENTERTAINMENT', 'Client Entertainment'), ('BILLS', 'Internet & Phone Bills'), ('HEALTHCARE', 'Healthcare'), ('MISC', 'General / Miscellaneous'), ('OTHERS', 'Others')], max_length=50),
        ),
    ]
