# Generated by Django 4.2.15 on 2025-12-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_alter_reimbursement_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(blank=True, choices=[('On Hold', ' On Hold'), ('In Verification', 'In Verification'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='On Hold', max_length=50, null=True),
        ),
    ]
