#----------- ----------------------API FOR SUPER ADMIN-------------------------


#api for generating token pair
###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "snv_arm_kak_117",
  "password": "password123"
}



# common logout for super admin,hr comapny,employee

###
POST http://178.248.112.16:8000//api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5Nzk1NTU0LCJpYXQiOjE3NDk3OTE5NTQsImp0aSI6IjI2YjNhZmE3ZDU1NTRiMDBiNTNmYTU1MmE2MmU4MzMyIiwidXNlcl9pZCI6MX0.nqiJ5M8wuC57RbmRKXJt1ckQXt8S1LdmzQ47JIK2smA
{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0ODk0MzcyNCwiaWF0IjoxNzQ4ODU3MzI0LCJqdGkiOiIzNTk1NDFkMjMzMzY0NGFjYmE1NWY4NTI5M2ZhNDM4ZiIsInVzZXJfaWQiOjJ9.XBDxkP19tY9Z_wBG4sRl4lYBWInp8H_B2qkafZFGIe8"
}

### Refresh Access Token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzMzODQ2MiwiaWF0IjoxNzUzMjUyMDYyLCJqdGkiOiIyOWQxM2QxMDRkOWE0MGY3OTgxMjJhZTA1ZTg5MWRjZSIsInVzZXJfaWQiOjEsImlzX3N1cGVyYWRtaW4iOnRydWUsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.Ymgt13k3alK8nEm2--yexqCd2vf3i2rRfOeBfwGUqb0"
}


# common change password for all users

### Change Password (Employee, HR, Superadmin)
POST http://localhost:8000/api/change-password/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5ODE4MDk0LCJpYXQiOjE3NDk4MTQ0OTQsImp0aSI6IjI0YjM4MDYzYTJlNzQ2MTI5ODg3MzM5OTBjYmU3MTRkIiwidXNlcl9pZCI6MTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.pjUe3KfOPzqvPH5m3LCnAOX040fuTA8kikqU3m5gFS8
Content-Type: application/json

{
  "old_password": "CMPX3PBGL801",
  "new_password": "123"
}





#api for creating companies
###
POST http://127.0.0.1:8000/api/create-company/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTI5NzYyLCJpYXQiOjE3NTIxMjYxNjIsImp0aSI6ImM2ODkwYzMzZmI5NTQwNjg4NGM2YjdmMGYwZjZiZGQ2IiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.AFTfZyEiETCkhEOrYhVL7r1M_uNa3DygWgPUVSL88bU

{
  "name": "tns",
  "address": "xyz street, kochi",
  "location": "kakanad",
  "country":"IN",
  "contact_number": "9996543210",
  "email": "tns@hgh.com",
  "modules": {
  "holiday": true,
  "payroll": true,
  "employee": true,
  "dashboard": true,
  "daily_task": true,
  "department": true
}
}



# list companies

### 
GET http://127.0.0.1:8000/api/companies/list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5ODAwMTg4LCJpYXQiOjE3NDk3OTY1ODgsImp0aSI6IjUwN2U3ZDY2YWM1OTQ1MGM4Zjc0N2U1ODIwMTkzMzcyIiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.jRqwHu5Nf9LbyWS4wokIbEwQ2LBxhBMtsQ5BqKVXtJo

# search comapny by name
###
GET http://127.0.0.1:8000/api/companies/list/?search=lumi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5ODA0NzEwLCJpYXQiOjE3NDk4MDExMTAsImp0aSI6Ijg5MjM0NzczMWU3NDRmMzk5NzkwZmQwZjE0ZmI1ZjQwIiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.aejv_GUBd-7esQC2AUjn_rNdnR7LA-Bs800v8ncgb00



### Get details of a single company (replace 1 with actual ID)
GET http://127.0.0.1:8000/api/companies/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDAzMjM3LCJpYXQiOjE3NTAzOTk2MzcsImp0aSI6IjA1NjU3OWYyMjkxNjRhNGRhYzIzMWRlODIyMzZkMDE4IiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.-igFKB4tGpVq37ZC8N_m-HSpjnN6OuiEXLbTxUesZQI




### Update a company (replace 1 with actual ID)
PUT http://127.0.0.1:8000/api/companies/6/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNjI4NTYyLCJpYXQiOjE3NTE2MjQ5NjIsImp0aSI6Ijk5NWQ0NjlmNWY0NDQ5NjVhNDBhZmM3MDI0MWMyZDgxIiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.J7mnzgwazpV3_2ebP-qO6pUh_dlsexFSEbXLIQQoipE

{
  "name": "XZY",
  "address": "xyz street, kochi",
  "location": "kakanad",
  "country":"IN",
  "contact_number": "9876543210",
  "email": "XYZ@hgh.com",
  "modules": {
  "holiday": true,
  "payroll": true,
  "employee": true,
  "dashboard": true,
  "daily_task": true,
  "department": true
}
}



### Delete a company with id
DELETE http://127.0.0.1:8000/api/companies/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTExODIwLCJpYXQiOjE3NDg1MDgyMjAsImp0aSI6ImMyYmMxZmRhNTMyNDQ3YjU5MmZlNmE0MzUxYmVlZThiIiwidXNlcl9pZCI6Mn0.3FUWk6avJUq1AmfRGZrip8RG9Bj5shf5Fw_u-HERfLw


# list subscription plan for comapany
###
GET http://127.0.0.1:8000/api/subscriptions/6/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNTYyMzA4LCJpYXQiOjE3NTI1NTg3MDgsImp0aSI6ImQ4NDhmOTY0ODEwYzRhZTdiMWM4OWUyNzczY2M2ZGEyIiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.YKA6eEG-JqtDbyd1rlCMExqDJSRx-kKvOoFK06TWnNk
# update subscription status for company
###
PUT http://localhost:8000/api/subscriptions/mark-paid/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDA5NzE3LCJpYXQiOjE3NTA0MDYxMTcsImp0aSI6IjMwYzM4NmQ0ZDcwZjRlZmNhMmYwMjk2ODA1Mzk0ZjJiIiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.9jO_r8Uiwrw9vmGLIAS6oB-kEy919wlv1AEuV4o7H-c

# api for email
###
POST http://localhost:8000/api/invoice/send-email/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODI5NDYwLCJpYXQiOjE3NTA4MjU4NjAsImp0aSI6IjY4ZjcyZmQ3Njk5ZjRmOWM5ZTExNjY0ZGQ4ZGM4NDlhIiwidXNlcl9pZCI6MSwiaXNfc3VwZXJhZG1pbiI6dHJ1ZSwiaXNfaHJfYWRtaW4iOmZhbHNlLCJpc19lbXBsb3llZSI6ZmFsc2V9.b9dwwb6DH9V6rNeSej61dbXpXuGcGCySAz16wtjToDo
Content-Type: application/json

{
  "entry": {
    "month_display": "June",
    "year": 2025,
    "amount": 299.99,
    "status": "Paid",
    "paid_date": "2025-06-20",
    "currency": "USD"
  },
  "email": "customer@example.com",
  "company_name": "Tungston Labs"
}


# ----------------------------API FOR HR ADMIN:HR COMPANY--------------------------------

# API for generating token pair for company HR


###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "snv_arm_kak_117",     
  "password": "password123"  
}




# API for creating department.
###
POST http://127.0.0.1:8000/api/departments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5NzExNjkzLCJpYXQiOjE3NDk3MDgwOTMsImp0aSI6ImZjM2M5ZjlhMWJkOTRkMGZhMmUzZTU0ODM4MjNjOTRiIiwidXNlcl9pZCI6M30.YMx-WBBSHdmilhjQaEdmSfEf81zK4ELDXryDV7FsLAA

{
  "name": "Manufacturer",
  "department_code": "M001",
  "department_head": ""
}


# list departments

###
GET http://178.248.112.16:8001/api/departments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU3MzEyMjE1LCJpYXQiOjE3NTczMDg2MTUsImp0aSI6ImMzZmIwOThlZjE5ZjQzZWU4ZGQzZWI3NGI4MmNmYjZlIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.cp0I1umSVI6tbufeZDdfOhTmEVJ4ZTbrXacGrRY1qpE


# retrieve single department
###
GET http://127.0.0.1:8000/api/departments/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg0MzkwLCJpYXQiOjE3NDg1ODA3OTAsImp0aSI6IjUxNzAyOWQ0YmE5ODRjYWNiYWVjYjA5MmM2NzA0ZjNhIiwidXNlcl9pZCI6M30.-asuZE8TxamUfRkqPdlgge2Xa5tdCRRfEVqFc1r9zDs

# update department details

###
PUT http://127.0.0.1:8000/api/departments/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg0MzkwLCJpYXQiOjE3NDg1ODA3OTAsImp0aSI6IjUxNzAyOWQ0YmE5ODRjYWNiYWVjYjA5MmM2NzA0ZjNhIiwidXNlcl9pZCI6M30.-asuZE8TxamUfRkqPdlgge2Xa5tdCRRfEVqFc1r9zDs

{
  "name": "HR and Admin",
  "department_code": "HR001",
  "department_head": "Ann Mathew"
}

# delete department

###
DELETE http://127.0.0.1:8000/api/departments/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg0MzkwLCJpYXQiOjE3NDg1ODA3OTAsImp0aSI6IjUxNzAyOWQ0YmE5ODRjYWNiYWVjYjA5MmM2NzA0ZjNhIiwidXNlcl9pZCI6M30.-asuZE8TxamUfRkqPdlgge2Xa5tdCRRfEVqFc1r9zDs


# api for search department by name
###
GET http://127.0.0.1:8000/api/departments/?search=testing
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg4Mjc4LCJpYXQiOjE3NDg1ODQ2NzgsImp0aSI6Ijk4NTIxZTJhYTA2ZDRjZTQ5YjMxYjg4Yzc0MzRmNmI0IiwidXNlcl9pZCI6M30.BJdURp0KOHB_9FzVqeyyJ9ZQuxYXE_fjeFJaYWR0Slk

# api for getiing employees with department id
###
GET http://127.0.0.1:8000/api/employees/department/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMDY2Nzg4LCJpYXQiOjE3NTAwNjMxODgsImp0aSI6ImI2Mjk1MGFlOWE5NzQyZmNhMTkxMjIxMDg3NzQ0MmQ5IiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.VLVVTVqe49ENkC_a0B6xrmozoNYG4RjHluPhpgm8GrE

# create employee


###
POST http://127.0.0.1:8000/api/employees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODUwODcwLCJpYXQiOjE3NDg4NDcyNzAsImp0aSI6IjQ1N2ExNTg0NjE2ODQxZjNhZDRmYWY3MjVkOTY4OTNhIiwidXNlcl9pZCI6M30.-wpOCf1K0F05-eEI5XhlbNTS__EUmH7l5qyZUwtuLeA
Content-Type: multipart/form-data; boundary=---011000010111000001101001


###

# create employee


###employee list according to department
GET http://178.248.112.16:8001/api/employees/?department_id=16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0Mjk1NDc2LCJpYXQiOjE3NTQyOTE4NzYsImp0aSI6IjI3N2U5NmEzMjVjOTQwMzlhNGQ3NzhmMmYwZTcyYjFmIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.hExg9tTqNXl1oYLjJku_WJFIidGXggBHmYhy2gHvV7E


# retrieve all employee

###
GET http://178.248.112.16:8001/api/employees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzUzMjk3LCJpYXQiOjE3NTU3NDk2OTcsImp0aSI6IjRkNjUwMDVjZTU3YjQ4MmFiYzVhYzE5YWEzZjBjZDQyIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.3TsQu6OMF_SNk3AAOjGzqGJZZex5vX5gzFlCYn3C3Mg
### employee list without pagination
GET http://178.248.112.16:8001/api/employeelist/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzUzMjk3LCJpYXQiOjE3NTU3NDk2OTcsImp0aSI6IjRkNjUwMDVjZTU3YjQ4MmFiYzVhYzE5YWEzZjBjZDQyIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.3TsQu6OMF_SNk3AAOjGzqGJZZex5vX5gzFlCYn3C3Mg
# retrieve one employee with id
###
GET http://127.0.0.1:8000/api/employee/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODQxNTI0LCJpYXQiOjE3NDg4Mzc5MjQsImp0aSI6ImY4MDk3NTcwM2MxMjQ3NjE5MDVlYjkxMzg5ZmJhYzZhIiwidXNlcl9pZCI6M30.sE782ASoxMZwkoJ6OFuclpEgdF5GIGlMRZAe72TImoI

# update employee


# delete employee
###
DELETE  http://127.0.0.1:8000/api/employees/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMTQ3ODMzLCJpYXQiOjE3NTAxNDQyMzMsImp0aSI6IjA3ZjgxOTVmZDVkZjRlOTY5ZDA5OTlmNzQyMTc5ZDlhIiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.Ravw7OppgukLgys_FLCqbaYAtC4TFCn_ib19FxrmR20

### Get employees visa expiry
GET http://178.248.112.16:8001/api/employees/upcoming-expiry/?type=visa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0NjU1MTYyLCJpYXQiOjE3NTQ2NTE1NjIsImp0aSI6IjgwNWRmN2Y1NWMxMDRmOTA4YWY1NWRkNjMwNWVjODEyIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.kHZf8YXjYwknqfFobCAczGG70C7V-xlctkta8URERIE
Accept: application/json


# search employee by name or ID

###
GET http://127.0.0.1:8000/api/employeelist/?search=HOMHR 3RM
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODQxNTI0LCJpYXQiOjE3NDg4Mzc5MjQsImp0aSI6ImY4MDk3NTcwM2MxMjQ3NjE5MDVlYjkxMzg5ZmJhYzZhIiwidXNlcl9pZCI6M30.sE782ASoxMZwkoJ6OFuclpEgdF5GIGlMRZAe72TImoI



#------------------ PAYROLL APIS FOR HR ADMIN-----------

# list all bank details + basic details employee

###
GET http://127.0.0.1:8000/api/employees/bank-details/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDcxOTQzLCJpYXQiOjE3NTI0NjgzNDMsImp0aSI6IjA1MWExYjJjZDliNDQzN2Q4YWIwNzBmZDQ5ZTA5MDkxIiwidXNlcl9pZCI6MzgsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.K6RMAH1rvBfW38E901XMYuCrb6BaHin8LewSOE65MAs

### Get payroll records for a specific month and year
GET http://localhost:8000/api/payroll/?month=7&year=2025&search=jesna
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDcxOTQzLCJpYXQiOjE3NTI0NjgzNDMsImp0aSI6IjA1MWExYjJjZDliNDQzN2Q4YWIwNzBmZDQ5ZTA5MDkxIiwidXNlcl9pZCI6MzgsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.K6RMAH1rvBfW38E901XMYuCrb6BaHin8LewSOE65MAs

### Create or update payroll records for selected employees
POST http://178.248.112.16:8001/api/payroll/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTgxMTQ4LCJpYXQiOjE3NTU1Nzc1NDgsImp0aSI6Ijk3NDgwMTRiYzU0MTRmNmQ5ZTE1MjM2NGI1OGVmZTUyIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlLCJpc19ociI6dHJ1ZX0.bOKexdPiiwTI3oqo_qP3TF3pB0sCdGh8bhp9gTLljNM

{
  "month": 7,
  "year": 2025,
  "employee_ids": [53],
  "status": "Paid"
}



###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "TUNNIL2OV",     
  "password": "EMPA9445373"  
}



### ✅ Verify Payroll for Employee
POST http://178.248.112.16:8001/api/payroll/53/verify/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTg4MDE5LCJpYXQiOjE3NTU1ODQ0MTksImp0aSI6IjIyNTdlMjQ4M2ViMzQ0NzE4ODA0MjZiMTY5N2VlYWRmIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlLCJpc19ociI6dHJ1ZX0.L6LplMx3qL20Z_3INGnV3XRzyp2JGS3ySNvxORsRRBY
Content-Type: application/json

{
  "month": 8,
  "year": 2025
}


### Update payroll status for a single employee (HR selects month/year)
PATCH http://178.248.112.16:8001/api/payroll/53/status/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NTgxMTQ4LCJpYXQiOjE3NTU1Nzc1NDgsImp0aSI6Ijk3NDgwMTRiYzU0MTRmNmQ5ZTE1MjM2NGI1OGVmZTUyIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlLCJpc19ociI6dHJ1ZX0.bOKexdPiiwTI3oqo_qP3TF3pB0sCdGh8bhp9gTLljNM

{
  "month": 7,
  "year": 2025,
  "status": "Pending"
}

# payroll record detail
###
GET http://localhost:8000/api/payroll/record/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzE3MTAzLCJpYXQiOjE3NTE3MTM1MDMsImp0aSI6IjcwZDhlN2E3MGMyYTQyMTk4ZmQyYjJiZmNkMDM3MmViIiwidXNlcl9pZCI6MzgsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.0Gfe_uVpYn-qVof491gdlSp4E5PCoOKOjPlX9oN50BY

# forgot password
###
POST http://178.248.112.16:8001/api/forgot-password/send-otp/
Content-Type: application/json

{
  "email": "tls@gmail.com"
}
# verify OPTIONS 
###
POST http://178.248.112.16:8001/api/forgot-password/verify-otp/
Content-Type: application/json

{
  "email": "tls@gmail.com",
  "otp": "441526"
}

# reset password after otp verification
###

POST http://178.248.112.16:8001/api/forgot-password/reset/
Content-Type: application/json

{
  "email": "tls@gmail.com",
  "new_password": "password123",
  "confirm_password": "password123"
}
###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "snv_arm_kak_117",     
  "password": "password123"  
}

### Get Employee Dashboard Details
GET http://178.248.112.16:8001/api/dashboard/employee/53/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDcwMDMwLCJpYXQiOjE3NTUwNjY0MzAsImp0aSI6ImY1NWYzMjA0NDJlNTQ3YmRhYjNlMDJkY2UyNDU3NGJmIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.1iKzTrp8Ns-kIeBs_w5pZAPWqPQe8hR2zxH3ZeC7BL4
# ----------------------------------API FOR EMPLOYEE-----------------------


###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "snv_arm_kak_117",     
  "password": "password123"  
}


# dashboard Summary 

###
GET http://178.248.112.16:8001/api/admin/dashboard-summary/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDY2MDM0LCJpYXQiOjE3NTUwNjI0MzQsImp0aSI6IjIwYzMyYjM0YjMxYzQyODBiMDEyZmZlNmFjZDk4NTdiIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.97462hxxamn026Acg3yy91vVTbu0le1IZ2oqjfayidg





# retirieve single bank details 
###
GET http://127.0.0.1:8000/api/bank-payments/28/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNDg1NzQ0LCJpYXQiOjE3NTA0ODIxNDQsImp0aSI6ImVmZDk2Yjg0NTlhOTQwMWM4MTY5YzA3MDdlODU4Y2QwIiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.ETHXCcVHI4KKcr3tCLwZvRGH_NzkW1JxjxjHl8AG7oo
# -----------------------------API FOR LEAVE-----------------



### List All Leaves (HR Admin)
GET http://127.0.0.1:8000/api/leave/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODM3MjE4LCJpYXQiOjE3NTA4MzM2MTgsImp0aSI6IjM4ZDVhMWM3NzI2YzRiNzJhMGRkZGQxMWI0MjRhOTc5IiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.xuQAcVUh5AjKZagoSCxsb8bhn47_7f71kyo3OtpyGMw



#### Get Leave Detail by ID (HR Admin)
GET http://127.0.0.1:8000/api/leave/admin/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODU0ODIzLCJpYXQiOjE3NDg4NTEyMjMsImp0aSI6Ijc3NTViNjMxMDc5NDQzNDE4ZTI3ZWY2YWI2YmYwODZkIiwidXNlcl9pZCI6M30.Me_MGEl8zfsWRUN84_wSRx-eDMswEtQAb6mj7wqW-P8



### Update Leave (HR Admin) – e.g., Approve or Reject
PATCH  http://127.0.0.1:8000/api/leave/admin/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTY0ODc4LCJpYXQiOjE3NTE5NjEyNzgsImp0aSI6IjdkY2ZlNTc2ZDM3NTQzNjdiZGJjNTZlNzUwMGZmZTY3IiwidXNlcl9pZCI6MzgsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.GhTWHkpdyhI98TQbp3o_z1pFzxdWjLTAyVepACDHgO0
Content-Type: application/json

{
  "status": "rejected"
  
}


### Delete Leave (HR Admin)
DELETE http://127.0.0.1:8000/api/leave/admin/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODU0ODIzLCJpYXQiOjE3NDg4NTEyMjMsImp0aSI6Ijc3NTViNjMxMDc5NDQzNDE4ZTI3ZWY2YWI2YmYwODZkIiwidXNlcl9pZCI6M30.Me_MGEl8zfsWRUN84_wSRx-eDMswEtQAb6mj7wqW-P8


### List All Leaves (HR Admin) according to status
GET http://178.248.112.16:8001/api/leave/admin/?status=pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MzQ0MTM5LCJpYXQiOjE3NTUzNDA1MzksImp0aSI6ImQyNWU2YTlhNzJmNjQyYzZhY2Y0ZjZkOTgwYjU1MTc2IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.hiQfQo3Q3xyoDo1WZkmt8nlTriYbR7zXqbLWUGT4hzw

### list employees on leave
GET http://178.248.112.16:8001/api/departments/16/on-leave-employees/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MzQ0MTM5LCJpYXQiOjE3NTUzNDA1MzksImp0aSI6ImQyNWU2YTlhNzJmNjQyYzZhY2Y0ZjZkOTgwYjU1MTc2IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.hiQfQo3Q3xyoDo1WZkmt8nlTriYbR7zXqbLWUGT4hzw
### list employees on same department who 
GET http://178.248.112.16:8001/api/department/53/on-leaves/?date=2025-08-21
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1Njg5MzY2LCJpYXQiOjE3NTU2ODU3NjYsImp0aSI6IjFkNGUwOGFjYzMzMjRjMTY5M2Y1YjVmM2VlYTEzN2Y1IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.Io9G8KvAvTgsC-LlgtfDARGR3JU1D7Q-N69DL-eBUPI

# =-------------------------API FOR TASK MANAGEMENT--------------------------


### Get Specific Task (Employee)
GET http://127.0.0.1:8000/api/employee/tasks/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODU5NDgzLCJpYXQiOjE3NDg4NTU4ODMsImp0aSI6IjgzZjdhNGUwNTNmNTQyMjY5NTc1MmQ2MTExYjJiMmJkIiwidXNlcl9pZCI6MTh9.DCOA_M_IZv5Cl5Yjql0th-biI78T45bebG0PFg88Yi8

### Update Task (Employee)
PUT http://127.0.0.1:8000/api/employee/tasks/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMTQxODExLCJpYXQiOjE3NTAxMzgyMTEsImp0aSI6IjEwYjljZTViM2RlNzQzMjA4NWQ5YTk2Mzg2OTkyZWM2IiwidXNlcl9pZCI6MjIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.fLXDeCVy27Sa_5byAYV3PWynmI53Ntgugi6v6QUtihM
Content-Type: application/json

{
  "project": "Project A",
  "task": "Updated: Fixed bugs in login flow",
  "time_taken": 4.0
}

### Delete Task (Employee)
DELETE http://127.0.0.1:8000/api/employee/tasks/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODU5NDgzLCJpYXQiOjE3NDg4NTU4ODMsImp0aSI6IjgzZjdhNGUwNTNmNTQyMjY5NTc1MmQ2MTExYjJiMmJkIiwidXNlcl9pZCI6MTh9.DCOA_M_IZv5Cl5Yjql0th-biI78T45bebG0PFg88Yi8


### List All Tasks (HR Admin)
GET http://127.0.0.1:8000/api/admin/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODU5OTEyLCJpYXQiOjE3NDg4NTYzMTIsImp0aSI6ImNmYTViNGEyZDg4YzQxZTJiNzM2ODMyNzM5ZWIzNzdmIiwidXNlcl9pZCI6M30.fUCQkANJ3_SYvBIB8djOGCrNaH1HvGqvcc5l98wKZoU

### HR Admin: List Tasks by Employee ID
GET http://178.248.112.16:8001/api/admin/tasks/employee/10/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMTQ3MDE0LCJpYXQiOjE3NTAxNDM0MTQsImp0aSI6IjJlZTc2N2ZlYzkyMjRlNzg4Y2VmN2Y4NDg1YWQzZTdlIiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.LGltLB6FrNheMhXJ8CUmWSlwPnB-MNEtp4rvn8Kt4t4

# -------------employee attendance------------------


### Swipe (Punch In/Out)
POST http://127.0.0.1:8000/api/attendance/swipe/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNzQ1Nzk0LCJpYXQiOjE3NTA3NDIxOTQsImp0aSI6ImEzODU5YTNiMTBlOTQ0MDdiZjRhMjllNWU5MzBlZWJkIiwidXNlcl9pZCI6NDMsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.a4D6kj8KCHObkgOD4s1UfVXaavoOlHu4F9TDpPA5VPc


# list out employee attendance for admin
###
GET http://178.248.112.16:8001/api/admin/attendance/?department_id=16
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTU0NjY1LCJpYXQiOjE3NTUxNTEwNjUsImp0aSI6IjUwMGY2ZGQ3MDQ4NTQzNmJhZmRhODhlMDA3ZWYwOGEwIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.Imu8QcW2Zz_BXBGbHxCUIMtnK8u7tpezZSfIpse1adY

# lst todays punch in punch outs
###
GET http://127.0.0.1:8000/api/attendance/today/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwMjQxOTQ1LCJpYXQiOjE3NTAyMzgzNDUsImp0aSI6IjI4MWQ5ODZjNjZhZTQyZWY5ODUyYzNkOGUyNWM4ZjM3IiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.BTsFlZA1_afrz9BSRQliKToGjCpLKMnhKw8127TDsS0


# attendance detail view(hr admin)

###
GET http://178.248.112.16:8001/api/admin/attendance/31/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1Njk0Njg5LCJpYXQiOjE3NTU2OTEwODksImp0aSI6ImQyNzAzZTg1ZmQ0NjRlNDlhMmViNmFmYzM5NjVmN2EyIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.Jaj-6CLHis1GLtjfHuKdbWkUwYCdf1hTWXmDL_xbJgE
# --------------PUBLIC HOLIDAY ----------------------------------

### Create Holiday
POST http://127.0.0.1:8000/api/holidays/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDcxMjU5LCJpYXQiOjE3NTI0Njc2NTksImp0aSI6IjZlMTU3MTRiZjkxZTQxYzg5YjkxNDk2YjcwNzlmNGJiIiwidXNlcl9pZCI6OTcsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.NakR6laItRMqpP-aa1MiiMehdBTQOkVUcOvhX1yN634
Content-Type: application/json

{
  "date": "2025-12-31",
  "description": "new year celebration",
  "holiday_type":"public"
}


### List Holidays (HR Admin)
GET http://127.0.0.1:8000/api/holidays/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwODM0MzE5LCJpYXQiOjE3NTA4MzA3MTksImp0aSI6IjAwOGE4M2UxY2IxYjQ5MGM5YmNjOWY0NmFmMWE4MGI3IiwidXNlcl9pZCI6MywiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2V9.tlA-Xh-OJFF-7rxwXoZ_dsQMNo3KAuscAGMxgfdaD64

### Get Single Holiday by ID
GET http://127.0.0.1:8000/api/holidays/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTI4NDM2LCJpYXQiOjE3NDg5MjQ4MzYsImp0aSI6IjM5ZGEzOGRiYjAyODRkOTM5ZDgxZjI1YTZlNTM4ZTkyIiwidXNlcl9pZCI6M30.9VK8uzpdHaP3_BcP2LKSGvrzzr9CdssbFRt41jgEwjs


### Update Holiday by ID
PUT http://127.0.0.1:8000/api/holidays/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTI4NDM2LCJpYXQiOjE3NDg5MjQ4MzYsImp0aSI6IjM5ZGEzOGRiYjAyODRkOTM5ZDgxZjI1YTZlNTM4ZTkyIiwidXNlcl9pZCI6M30.9VK8uzpdHaP3_BcP2LKSGvrzzr9CdssbFRt41jgEwjs
Content-Type: application/json

{
  "date": "2025-06-07",
  "description": "Eid"
}


### Delete Holiday
DELETE http://127.0.0.1:8000/api/holidays/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4OTI4NDM2LCJpYXQiOjE3NDg5MjQ4MzYsImp0aSI6IjM5ZGEzOGRiYjAyODRkOTM5ZDgxZjI1YTZlNTM4ZTkyIiwidXNlcl9pZCI6M30.9VK8uzpdHaP3_BcP2LKSGvrzzr9CdssbFRt41jgEwjs






#-------------------------------------------------------- API FOR MOBILE APPLICATION


# api for creating token pair for employee

###
POST http://178.248.112.16:8001/api/token/
Content-Type: application/json

{
  "username": "TUNGRAS82",     
  "password": "athul"
}
### 
GET http://127.0.0.1:8000/api/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyODQwNzQ5LCJpYXQiOjE3NTI4MzcxNDksImp0aSI6IjE2MjU0ZmEyYmY2YjQxM2Y4NjQ2OTBkNDBhNDZjMjBmIiwidXNlcl9pZCI6OTIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.c-EZW0OM4e4iyN3XV8QZI8cj0j4YWlA5TLTzTW37X6E




### Swipe (Punch In/Out)
POST http://178.248.112.16:8001/api/attendance/swipe/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0Mzc5Nzc2LCJpYXQiOjE3NTQzNzYxNzYsImp0aSI6Ijg3MjBkMjg1ZTU3OTQwZTY4MDMwNjhkZTdjNGY1Nzc4IiwidXNlcl9pZCI6NzMsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.wyr8YNbzlGpYEGHMnb_Cij7o7Twy05MaUMODpPofAB8

# list out employee attendance for admin
###
GET http://127.0.0.1:8000/api/admin/attendance/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MTU0MTE1LCJpYXQiOjE3NTUxNTA1MTUsImp0aSI6ImQ5MDg5YTlmOTMzNzQ3YmJiZGEyMjM1ZWM1YmYyYTMxIiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlLCJpc19ociI6ZmFsc2V9.xUTauo3dU-UttK9xeeHTnXbeApDWsWcTH423zNSxf4c

# lst todays punch in punch outs
###
GET http://178.248.112.16:8001/api/attendance/today/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU0ODk4MzE1LCJpYXQiOjE3NTQ4OTQ3MTUsImp0aSI6ImNmZWFjNmJiNTRmOTRmODg4NmM4YjJiYzIwZjZiZGUwIiwidXNlcl9pZCI6NzMsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.RgcG8gjGcZF_bnv2OQNxlZu27n9FtO8OlBRpSoQ8g0I

# api for listing employees of same department
###
GET http://127.0.0.1:8000/api/employees/my-department/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzODc0NjAyLCJpYXQiOjE3NTM4NzEwMDIsImp0aSI6ImIwZDgyODljNmIzZDRmMGE4Njk5MmIwZWZjZThhM2I2IiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.QHGVfWwW1urfQxTr8CHGpGN11jsn3WwzeafVplp2fAo


### List Holidays (Employee)
GET http://127.0.0.1:8000/api/holidays/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyNDY5NzAxLCJpYXQiOjE3NTI0NjYxMDEsImp0aSI6Ijc2MmUwY2EyMjlkZDQwMzA5YmM0NjczMmZlN2EzZTg2IiwidXNlcl9pZCI6NjksImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.DNYNmeFHa7Jw3YZ11Wa3FfznkZELLIXvE35yTC-jI84
# api for applying leave.

### Create Leave (Employee)
POST http://127.0.0.1:8000/api/leave/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzAyMTk2LCJpYXQiOjE3NTE2OTg1OTYsImp0aSI6ImM3OWU5ZWUwOWVmNDQxMjFhMjUyMjY0ODA1ODFiOWY2IiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.hPexAZkIQsI6OCSm9-ToXADkNoRODip-6CeuB2AjfhE
Content-Type: application/json

{
  "leave_type": "casual",
  "reason": "Casual",
  "from_date": "2025-09-02",
  "to_date": "2025-09-11",
  "to_email": "nisna@gmail.com",
  "cc_email": "nisnatls@gmail.com.com"
}



### List My Leaves (Employee)
GET http://127.0.0.1:8000/api/leave/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzMDg1ODQ2LCJpYXQiOjE3NTMwODIyNDYsImp0aSI6IjQ4MTI1NWRlNzY4ZDRlOTg5ZGI5Mzg3YjM1ZWFkMzg2IiwidXNlcl9pZCI6OTIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.v9L2FtOqi1oMdTp_0DhrAFfhyljDIrXTBkLik3DHamk
### Cancel My Pending Leave (Employee)
DELETE http://127.0.0.1:8000/api/leave/9/cancel/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTYyNTUzLCJpYXQiOjE3NTE5NTg5NTMsImp0aSI6ImEzYWNmYWVkOGYzYTQwODc4ZWFjODU3YmYzZmViNzI0IiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.z4sM7nO-dGRqcOTmU2rw6QHEAm4pmuPg6iNs94_s78M

###
GET http://127.0.0.1:8000/api/leave/by-status/?status=rejected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzExNDUzLCJpYXQiOjE3NTE3MDc4NTMsImp0aSI6Ijg1YzE0MGJlMTc5ZTQ0MGViMDY1N2UwOTYyNmI1ZjVhIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.l9BlUkbDK831kZGsMuQatC2_Ryv9sIZq-YY_AJsf-tk


###LEAVE COUNT SUMMARY

GET http://127.0.0.1:8000/api/leave/summary/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxNzExNDUzLCJpYXQiOjE3NTE3MDc4NTMsImp0aSI6Ijg1YzE0MGJlMTc5ZTQ0MGViMDY1N2UwOTYyNmI1ZjVhIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.l9BlUkbDK831kZGsMuQatC2_Ryv9sIZq-YY_AJsf-tk




### Create a Task (Employee)
POST http://127.0.0.1:8000/api/employee/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUxOTcxNzg4LCJpYXQiOjE3NTE5NjgxODgsImp0aSI6IjFlNjg2MjBmNmE2NjQ2MGVhOGI4ODEyMDc1NDdkZjA0IiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.kIL0sh2bFG4hL4PZFUe8E07Dpm1wN2ILr9vGBZAQlG4
Content-Type: application/json

{
  "project": "ABC",
  "task": "API INTEGRATION",
  "time_taken": 3.5 
}

### List Own Tasks (Employee)
GET http://127.0.0.1:8000/api/employee/tasks/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTIzODkzLCJpYXQiOjE3NTIxMjAyOTMsImp0aSI6IjBkODdlMDMxZDBlYzQyODM4NjAxYjk4NzdhYzg0ODdhIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.tkMEtX_OEG4d1FGYE__IqXspjMel_-16roER3QfQn9Y
###payroll self view for employee

GET http://127.0.0.1:8000/api/employee/payslips/?year=2025
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTQ4MzIwLCJpYXQiOjE3NTIxNDQ3MjAsImp0aSI6Ijc5YzdmN2RmNjU4NzQzYzFhYzc2ZTk0ZjdiMGM2NDI1IiwidXNlcl9pZCI6NjksImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.-m354Xp-4BqMLDI15X6kZ03_j9ozB0ERsqBxq7dpMuU
###employee details
GET http://localhost:8000/api/employee/document-summary/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTQxMTU5LCJpYXQiOjE3NTIxMzc1NTksImp0aSI6ImRiODk1ZTcyOTllMTRhOTU4MDNiOGMzMTdkNmU1ODkxIiwidXNlcl9pZCI6NjksImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.hjhsCEW5efBq5CVXObk6cYPdmIltlHY8BLxSzoSTWBQ
Content-Type: application/json


###employee details
GET http://localhost:8000/api/employees/48/documents/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMTMxMTc2LCJpYXQiOjE3NTIxMjc1NzYsImp0aSI6IjBhYzUyN2QwZjFhMDQ0NWU4MDFmNjcyYTdiNTc5MzVhIiwidXNlcl9pZCI6NzAsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.OYPrEjhxNI6yquehjHATQkKWZ1flcnmEmIlRESIakhQ
Content-Type: application/json



###PAYSLIP FOR EMPLOYEE
GET http://localhost:8000/api/employee/payslip/download/?month=07&year=2025
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUyMjA4MDA1LCJpYXQiOjE3NTIyMDQ0MDUsImp0aSI6IjBlMmViNDM4NjlmMzQ5NmM4NTE4MWUxZTFmNWFhMzc3IiwidXNlcl9pZCI6NjksImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.JhiuxkwcWdIgiaMpqI-tuPvWZoQJeK3RbKGJ-1hAsi8


#api for getting employees attendance details
### 
GET http://localhost:8000/api/attendance/summary/?month=2025-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzODY1MzQ1LCJpYXQiOjE3NTM4NjE3NDUsImp0aSI6ImZkMGI2ZWQwMmYwNDRmMjM5YTNmNjExMjNlNjA0MzNjIiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.YI9aiNaDDaX_uz1XpPTGxfIYdPVkggdib5yRDZeR1qA

###punchout note
PATCH http://localhost:8000/api/attendance/add-note/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUzODc0NjAyLCJpYXQiOjE3NTM4NzEwMDIsImp0aSI6ImIwZDgyODljNmIzZDRmMGE4Njk5MmIwZWZjZThhM2I2IiwidXNlcl9pZCI6OTUsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.QHGVfWwW1urfQxTr8CHGpGN11jsn3WwzeafVplp2fAo

{
  "note": "Left early due to a dentist appointment"
}


###schedule reminder
POST http://178.248.112.16:8001/api/reminders/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MjcxMzkyLCJpYXQiOjE3NTYyNjc3OTIsImp0aSI6ImRhZTY0ODg5YjUwMTQ3Yzk4ZTc4NWVkNTY4MmJlOWQ4IiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.T2IXH7yIygORpxAkomagGEfZHjT3M9yuRsgv3EsDf_s

{
  "title": "Project Deadline",
  "body": "Submit project report before end of day",
  "scheduled_datetime": "09:45"
}

### employee monthly summary for mobile app

GET http://178.248.112.16:8001/api/employee-monthly-summary/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDYxNjk0LCJpYXQiOjE3NTUwNTgwOTQsImp0aSI6IjM2YjViN2E4MDhkNjQzMTQ4YTQ2ODAyMTVlZDFlMGFiIiwidXNlcl9pZCI6NzMsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6ZmFsc2UsImlzX2VtcGxveWVlIjp0cnVlfQ.vFhQUJt1v4L5pDojod3VeHhDwPOdjf7kIx3hkQTKkjs
Content-Type: application/json
# attendance detail view(hr admin)

###
GET http://178.248.112.16:8001/api/admin/attendance/53/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDY5NDE5LCJpYXQiOjE3NTUwNjU4MTksImp0aSI6IjFmOTQ1MTI4MTljMTQxNGM4MGZhMzUyZGNkNmZlZmQ4IiwidXNlcl9pZCI6NzIsImlzX3N1cGVyYWRtaW4iOmZhbHNlLCJpc19ocl9hZG1pbiI6dHJ1ZSwiaXNfZW1wbG95ZWUiOmZhbHNlfQ.lfUVZax20FJm_OsHmNEI0SSZBalit5RwZ0bSWJuG7O8




# -----REIMBURSMENT MODULE------

###add 
POST http://178.248.112.16:8001/api/reimbursements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTM3NTI0LCJpYXQiOjE3NTU5MzM5MjQsImp0aSI6IjIzM2YzYjQ4ODgwNDRkOGFiYWI1OWZmNjU5NTY0NmQ2IiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.ib5BAbyjtBs2zhxHJvXwauLIoRObe42u9Yae6hDwVc4
Content-Type: multipart/form-data

{
  "expense_category": "TRAVEL",
  "to_mail": "manager@example.com",
  "note": "Taxi fare",
  "date": "2025-08-23",
  "amount": "100.50",
  "uploaded_images": ["<file1>", "<file2>"]
}

###list
GET http://178.248.112.16:8001/api/reimbursements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTM3NTI0LCJpYXQiOjE3NTU5MzM5MjQsImp0aSI6IjIzM2YzYjQ4ODgwNDRkOGFiYWI1OWZmNjU5NTY0NmQ2IiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.ib5BAbyjtBs2zhxHJvXwauLIoRObe42u9Yae6hDwVc4
Content-Type: application/json


###retrieve single record
GET http://178.248.112.16:8001/api/reimbursements/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MTAzOTg5LCJpYXQiOjE3NTYxMDAzODksImp0aSI6IjEwYTM3N2U1NGZlMDRiM2NhOWRlZDg0YzUwMzBjMGM1IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.Qz_3MCiQu1yvYmV6Q3z4lBk6mdHyjZKVoW87MVXhOt8
Content-Type: application/json


###list by department
GET http://178.248.112.16:8001/api/reimbursements/department/16/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MTAzOTg5LCJpYXQiOjE3NTYxMDAzODksImp0aSI6IjEwYTM3N2U1NGZlMDRiM2NhOWRlZDg0YzUwMzBjMGM1IiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.Qz_3MCiQu1yvYmV6Q3z4lBk6mdHyjZKVoW87MVXhOt8
Content-Type: application/json


### update status by admin
PATCH http://178.248.112.16:8001/api/reimbursements/1/   
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1OTQ3MzIzLCJpYXQiOjE3NTU5NDM3MjMsImp0aSI6ImY2MWI1ZGRiMzNmNjRkNmQ4YWZiNzQ4MzgyM2ZhOWMxIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.v9J6EIDOlBGNdWhowz-efW1hyglW03_wbwRyDRlrWSE
Content-Type: application/json

{
  "status": "Approve"
}

### Get reimbursements grouped by date
GET http://178.248.112.16:8001/api/reimbursements/grouped/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MDk5OTI1LCJpYXQiOjE3NTYwOTYzMjUsImp0aSI6ImVlZWE5MzE4YmI4NDQzZTdhNjYzZGQ5ZmI2OTJhYThlIiwidXNlcl9pZCI6IjcyIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjp0cnVlLCJpc19lbXBsb3llZSI6ZmFsc2UsImlzX2hyIjpmYWxzZX0.0kBTS1wWLMJS2dAypCpqj7B1_yGMgjDIF_Yy8Xd9KaM




### 1️⃣ List logged-in employee reimbursements
GET http://178.248.112.16:8001/api/reimbursements/my-reimbursements/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzgzOTYxLCJpYXQiOjE3NTYzODAzNjEsImp0aSI6ImU1ZTg1ZGI4NTdhMzQyYzg4NGI4ODA4M2ZlN2Y1ZDMxIiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.OsyrBCizOWZrIkWZurycQSMeiRNbLPBVbojcfS_4kP8
Content-Type: application/json

###

### 2️⃣ Retrieve a single reimbursement by ID
GET http://178.248.112.16:8001/api/reimbursements/my-reimbursements/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU2MzgzOTYxLCJpYXQiOjE3NTYzODAzNjEsImp0aSI6ImU1ZTg1ZGI4NTdhMzQyYzg4NGI4ODA4M2ZlN2Y1ZDMxIiwidXNlcl9pZCI6IjczIiwiaXNfc3VwZXJhZG1pbiI6ZmFsc2UsImlzX2hyX2FkbWluIjpmYWxzZSwiaXNfZW1wbG95ZWUiOnRydWUsImlzX2hyIjpmYWxzZX0.OsyrBCizOWZrIkWZurycQSMeiRNbLPBVbojcfS_4kP8
Content-Type: application/json

###

### 3️⃣ Delete a single reimbursement by ID
DELETE http://178.248.112.16:8001/api/reimbursements/my-reimbursements/1/
Authorization: Bearer {{accessToken}}
Content-Type: application/json
